/*
 * PaymentBox.java
 *
 * Created on Jun 4, 2010, 10:53:54 PM
 */

package com.pratikabu.expart.boundary;

import com.pratikabu.expart.components.AmountInfo;
import com.pratikabu.expart.components.UsefulMethods;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Blue
 */
public class PaymentBoxEqually extends javax.swing.JDialog {
    private AmountInfo ai = new AmountInfo();
    private ArrayList<AmountInfo> vectAI;

    private ArrayList<String> vectPaymentModeNames = new ArrayList<String>();
    private ArrayList<Integer> vectPaymentModeIDs = new ArrayList<Integer>();

    /** Creates new form PaymentBox */
    private PaymentBoxEqually(java.awt.Dialog parent, ArrayList<AmountInfo> vectAI) {
        super(parent, true);
        initComponents();

        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we){
                jButton1ActionPerformed(null);
            }
        });

        this.getRootPane().setDefaultButton(jButton2);
        
        this.vectAI=vectAI;

        renderAI();
        setLocationRelativeTo(parent);
        setVisible(true);
    }

    public static AmountInfo showPaymentBoxEqually(java.awt.Dialog paren, ArrayList<AmountInfo> ai){
        if(ai.isEmpty()){
            JOptionPane.showMessageDialog(paren, "No payee has been added.\n"
                    + "Atleast one payee should be added to continue.", "No Payee Added", JOptionPane.INFORMATION_MESSAGE);
            return null;
        }

        if ( ai.size() == 1)
            return ai.get(0);
        
        return new PaymentBoxEqually(paren, ai).ai;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Mode");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Payment Mode:");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "qw" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ai=null;
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ensureReturnAmount();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void ensureReturnAmount() {
        int row = this.jList1.getSelectedIndex();
        if (row != -1) {
            int selectedPaymentMode = vectPaymentModeIDs.get(row);
            ai.setPaymentMode(selectedPaymentMode);

            ai.setAmount(-1);//explicitly set it to negetive quantity, so that it can be catched at the transaction page

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Payment mode is not selected.");
            jList1.requestFocus();
        }
    }

    private void renderAI() {
        if (vectAI != null) {
            fetchAndSaveSelectedPaymentModes();
        }
    }

    private void fetchAndSaveSelectedPaymentModes() {
        for(AmountInfo tempAI : vectAI){
            vectPaymentModeIDs.add(tempAI.getPaymentMode());
            vectPaymentModeNames.add(UsefulMethods.getPaymentModeString(tempAI.getPaymentMode()));
        }

        jList1.setListData(vectPaymentModeNames.toArray());

        jList1.setListData(vectPaymentModeNames.toArray());
        try {
            jList1.setSelectedIndex(0);
        } catch (Exception e) {
        }
    }
}
