/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PaymentBox.java
 *
 * Created on Jun 4, 2010, 10:53:54 PM
 */

package com.pratikabu.expart.boundary;

import com.gmail.pratikabu.pls.controller.DatabaseController;
import com.pratikabu.expart.components.AmountInfo;
import com.pratikabu.expart.components.CurrencyTextField;
import com.pratikabu.expart.components.UsefulMethods;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Blue
 */
public class PaymentBox extends javax.swing.JDialog {
    private AmountInfo ai = new AmountInfo();
    private ArrayList<AmountInfo> vectAI;

    private ArrayList<String> vectPaymentModeNames = new ArrayList<String>();
    private ArrayList<Integer> vectPaymentModeIDs = new ArrayList<Integer>();

    /** Creates new form PaymentBox */
    private PaymentBox(java.awt.Dialog parent, ArrayList<AmountInfo> vectAI) {
        super(parent, true);
        initComponents();

        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we){
                jButton1ActionPerformed(null);
            }
        });

        this.getRootPane().setDefaultButton(jButton2);
        
        this.vectAI=vectAI;

        renderAI();
        setLocationRelativeTo(parent);
        setVisible(true);
    }

    public static AmountInfo showPaymentBox(java.awt.Dialog paren){
        return new PaymentBox(paren, null).ai;
    }

    public static AmountInfo showPaymentBox(java.awt.Dialog paren, ArrayList<AmountInfo> ai){
        if(ai.isEmpty()){
            JOptionPane.showMessageDialog(paren, "No payee has been added.\n"
                    + "Atleast one payee should be added to continue.", "No Payee Added", JOptionPane.INFORMATION_MESSAGE);
            return null;
        }
        return new PaymentBox(paren, ai).ai;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new CurrencyTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Payment Box");

        jLabel1.setText("Amount (Could be an expression):");

        jTextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setText("Eg: (50+43-2)*23");

        jLabel3.setText("Payment Mode (In which the payment is made):");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "It" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ai=null;
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ensureReturnAmount();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode()==evt.VK_ESCAPE)
            jButton1ActionPerformed(null);
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        paymentModeChanged();
    }//GEN-LAST:event_jList1ValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void ensureReturnAmount() {
        double amt = ((CurrencyTextField) jTextField1).getAmount();
        int row = this.jList1.getSelectedIndex();
        if (amt > 0 && row != -1) {
            ai.setAmount(amt);
            int selectedPaymentMode = vectPaymentModeIDs.get(row);
            ai.setPaymentMode(selectedPaymentMode);

            this.dispose();
        } else if(row == -1) {
            JOptionPane.showMessageDialog(this, "Payment mode is not selected.");
            jList1.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Amount cannot be negative or zero.");
            jTextField1.requestFocus();
            jTextField1.selectAll();
        }
    }

    private void renderAI() {
        if (vectAI != null) {
            fetchAndSaveSelectedPaymentModes();
            paymentModeChanged();
        } else {
            //fetch all payment types from the database
            fetchAndSaveAllPaymentModes();
            
            //set 0.00 and payment mode as cash
            ((CurrencyTextField) jTextField1).setAmount(0.0);
        }
    }private void fetchAndSaveSelectedPaymentModes() {
        for(AmountInfo tempAI : vectAI){
            vectPaymentModeIDs.add(tempAI.getPaymentMode());
            vectPaymentModeNames.add(UsefulMethods.getPaymentModeString(tempAI.getPaymentMode()));
        }

        jList1.setListData(vectPaymentModeNames.toArray());
        try {
            jList1.setSelectedIndex(0);
        } catch (Exception e) {
        }
    }

    private void fetchAndSaveAllPaymentModes() {
        String sql="SELECT * " +
                "FROM PaymentMode";

        DatabaseController dbc=new DatabaseController();
        ResultSet rset=dbc.getQueryResultSet(sql, new Object[]{});

        try{
            while(rset.next()){
                vectPaymentModeIDs.add(rset.getInt(1));
                vectPaymentModeNames.add(rset.getString(2));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error fetching Payment Types from Database.", "Eh..", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }finally{
            dbc.closeConnection();
        }

        jList1.setListData(vectPaymentModeNames.toArray());
        try {
            jList1.setSelectedIndex(0);
        } catch (Exception e) {
        }
    }

    private void paymentModeChanged() {
        int row = this.jList1.getSelectedIndex();
        if(vectAI != null && row != -1){
            int selectedPaymentMode = vectPaymentModeIDs.get(row);
            double amount=0.0;
            for(AmountInfo ai : vectAI)
                if(ai.getPaymentMode() == selectedPaymentMode){
                    amount = ai.getAmount();
                    break;
                }
            ((CurrencyTextField) jTextField1).setAmount(amount);
        }
    }
}
